platform: linux

inputs:
- name: zookeeper_bosh_release
- name: zookeeper_bosh_release_version
- name: zookeeper_bosh_candidate_release_s3

outputs:
- name: release_tarball
- name: updated_zookeeper_bosh_release

run:
  path: /bin/bash
  args: ["zookeeper_bosh_release/ci/tasks/create_final_release/task.sh"]