platform: linux

inputs:
- name: zookeeper_bosh_release
- name: zookeeper_bosh_release_version

outputs:
- name: release_tarball

run:
  path: /bin/bash
  args: ["zookeeper_bosh_release/ci/tasks/create_candidate_release/task.sh"]